import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TunzaMalkia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen  bg-gradient-to-r from-indigo-600  to-fuchsia-400 relative flex flex-col">
          <Navbar className="" />
          <div className="flex-1 h-full overflow-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
